export const profile = {
  name: "Zakaria Bendida",
  role: "Full-Stack Developer",
  location: "Algeria",
  email: "zakibendida700@gmail.com",
  phone: "+213 000 000 000",
  photo: "/zaki.png",
  photoAlt: "Portrait of Zakaria Bendida",
  availability: "Information Systems Engineering student",
  intro:
    "I build complete web applications from clean responsive interfaces to back-end logic, databases, validation, and deployment.",
  summary:
    "I am Zakaria Bendida, a 5th-year computer science student and information systems engineer in training. I build full-stack systems with React, Next.js, Node.js, databases, real-time communication, GIS tools, and practical UI design with Figma.",
  socials: {
    github: "https://github.com/Zakaria-Bendida",
    linkedin: "https://linkedin.com/",
    instagram: "https://instagram.com/",
    x: "https://x.com/",
    cv: "/CV_Bendida_FullStack_DeepNavy.pdf",
  },
  stats: [
    { value: "5th", label: "University year" },
    { value: "5+", label: "Full-stack projects" },
    { value: "GIS", label: "Master project" },
  ],
  highlights: [
    {
      title: "Education",
      text: "5th-year computer science student focused on information systems engineering.",
    },
    {
      title: "Courses",
      text: "Completed practical courses by Jonas Schmedtmann in React, JavaScript, Node.js, HTML, and CSS.",
    },
    {
      title: "Back-end & Databases",
      text: "Comfortable with Node.js, PHP, MySQL, MongoDB, Java, relational databases, and REST-style application logic.",
    },
    {
      title: "Design & Modeling",
      text: "Studied database design, relational database concepts, and interface design with Figma.",
    },
    {
      title: "Algorithms & Systems",
      text: "Studied algorithms, operating systems, graph theory, and graph algorithms such as A*, Dijkstra, and related path-finding methods.",
    },
    {
      title: "Networks & Real-time",
      text: "Practiced client-server networking exercises, server/client communication, and real-time concepts with Socket.IO.",
    },
  ],
  skills: [
    "React",
    "Next.js",
    "JavaScript",
    "Node.js",
    "Express",
    "PHP",
    "Java",
    "MySQL",
    "PostgreSQL",
    "PostGIS",
    "pgRouting",
    "Supabase",
    "MongoDB",
    "Docker",
    "Relational Databases",
    "Database Design",
    "HTML",
    "CSS",
    "Figma",
    "Vite",
    "Form Validation",
    "Algorithms",
    "Graph Theory",
    "A*",
    "Dijkstra",
    "Operating Systems",
    "Networking",
    "Client/Server",
    "Socket.IO",
    "OpenLayers",
    "React Native",
    "Expo",
    "GitHub",
    "Responsive Design",
    "Git",
  ],
  services: [
    {
      title: "Full-Stack Web Apps",
      text: "Complete applications with React interfaces, back-end logic, database integration, and clean project structure.",
    },
    {
      title: "Admin Dashboards",
      text: "Management systems with roles, tables, forms, validation, and workflows for real business operations.",
    },
    {
      title: "Forms & Validation",
      text: "Smart forms with strong input rules, such as blocking numbers in name fields and preventing invalid characters.",
    },
  ],
  projects: [
    {
      title: "Fast Emergency Dispatch Algeria (FEDZ)",
      type: "Master ISI Final Project - GIS Ambulance Dispatch Platform",
      text: "Real-time web and mobile ambulance dispatch platform for Sidi Bel Abbes. It combines live GPS tracking, blocked-road management, and intelligent routing with fast and fragile-patient comfort modes.",
      tags: [
        "PostgreSQL",
        "PostGIS",
        "pgRouting",
        "Node.js",
        "Express",
        "Socket.IO",
        "React",
        "OpenLayers",
        "React Native",
        "Expo",
      ],
      featured: true,
      image: "/projects/fedz.png",
      imageAlt:
        "FEDZ dashboard with OpenLayers map and live ambulance tracking",
      details: [
        {
          icon: "Route",
          title: "Dijkstra Routing",
          text: "Hourly congestion factors and traffic zone awareness",
        },
        {
          icon: "Zap",
          title: "Sub-200ms Calculations",
          text: "Route computation tested on 9,000 real OSM road segments",
        },
        {
          icon: "Radio",
          title: "Live GPS Tracking",
          text: "WebSocket location updates every 5 seconds",
        },
        {
          icon: "HeartPulse",
          title: "Dual Medical Modes",
          text: "Vital emergency and fragile-patient comfort routing",
        },
        {
          icon: "Server",
          title: "Production Deployment",
          text: "Hosted on Railway and Neon.tech",
        },
      ],
      stats: [
        { value: "<200ms", label: "Route calc" },
        { value: "9,000+", label: "OSM segments" },
        { value: "5s", label: "GPS refresh" },
        { value: "2", label: "Medical modes" },
      ],
      about:
        "This final-year engineering project reproduces a real ambulance dispatch system, with a focus on routing performance, live tracking, and GIS accuracy.",
      meta: {
        type: "Academic Project",
        year: "2026",
        stack: "MERN + GIS",
        status: "Completed",
      },
      note: "Master ISI final-year project, Universite Djillali Liabes, 2026.",
    },
    {
      title: "Saudi eVisa - Digital Visa Request Platform",
      type: "Academic coursework project (TP) - Full-stack visa application system",
      text: "A responsive full-stack MERN application that digitizes Saudi Arabia's official multi-page visa application form into a guided, multi-step web experience - covering applicant identity, passport details, travel purpose, accompanying family members, and administrative use, with real-time validation and file upload.",
      tags: ["React", "Vite", "Node.js", "Express", "MongoDB", "REST API"],
      image: "/projects/demande.png",
      imageAlt: "Saudi eVisa digital visa request platform screenshot",
      link: "lien-vers-ton-projet-deploye",
      details: [
        {
          icon: "Layers",
          title: "Multi-step wizard (4 stages)",
          text: "Progress tracker and per-section required-field validation",
        },
        {
          icon: "Code2",
          title: "Script-aware input filtering",
          text: "Arabic-only and Latin-only fields enforced via Unicode regex (RTL support included)",
        },
        {
          icon: "Users",
          title: "Dynamic family members table",
          text: "Add travelers on the same passport, on-demand",
        },
        {
          icon: "CalendarClock",
          title: "Auto-calculated length of stay",
          text: "From arrival/departure dates with edge-case guards",
        },
        {
          icon: "Upload",
          title: "Photo upload with live preview",
          text: "Submitted as multipart/form-data to the backend",
        },
        {
          icon: "Flag",
          title: "Nationality picker (40+ countries)",
          text: "With flag icons, built without any paid API",
        },
        {
          icon: "Database",
          title: "REST API (Node.js/Express)",
          text: "Persisting structured applications and uploaded documents",
        },
      ],
      stats: [
        { value: "4", label: "Steps" },
        { value: "100%", label: "Real-time validation" },
        { value: "Multi", label: "File upload" },
        { value: "REST", label: "API backend" },
      ],
      about:
        "This academic project reproduces a real multi-step visa application system, with careful attention to data validation, UX, file handling, and a robust API.",
      meta: {
        type: "Academic Project",
        year: "2024",
        stack: "MERN Stack",
        status: "Completed",
      },
      note: "Practical coursework project (TP), 2024.",
    },
    {
      title: "FoodApp - Multi-Branch Food Ordering Platform",
      type: "Final-year Licence project (ISIL - Ingénierie des Systèmes d'Information et Logiciels) - Full-stack multi-branch food ordering & delivery management platform",
      text: "A full-stack food ordering platform built from scratch, covering the entire flow from browsing a menu to checkout, plus a role-based admin system that automatically routes orders to the correct restaurant branch based on the customer's wilaya - with a live analytics dashboard, a review/rating system, and a complete order lifecycle for delivery tracking.",
      tags: [
        "React",
        "Vite",
        "Tailwind CSS",
        "Node.js",
        "Express",
        "Supabase",
        "PostgreSQL",
        "Recharts",
      ],
      image: "/projects/foodapp.png",
      imageAlt: "FoodApp multi-branch food ordering platform screenshot",
      link: "lien-vers-ton-projet-deploye",
      details: [
        {
          icon: "MapPin",
          title: "Wilaya-based branch routing",
          text: "Orders are automatically assigned to the restaurant branch covering the customer's wilaya - or rejected if none does",
        },
        {
          icon: "ShieldCheck",
          title: "Role-based admin access",
          text: "Super admin manages all branches; branch admins only see and manage their own branch's orders and stock",
        },
        {
          icon: "Star",
          title: "Live product ratings & reviews",
          text: "Customers rate dishes after ordering; approved reviews surface on the public About page in real time",
        },
        {
          icon: "BarChart3",
          title: "Interactive admin dashboard",
          text: "Recharts-powered order volume, revenue, and per-product rating charts computed from live order data",
        },
        {
          icon: "Lock",
          title: "Secure authentication",
          text: "bcrypt password hashing, httpOnly JWT cookies, rate-limited auth endpoints, and Supabase row-level security",
        },
        {
          icon: "Truck",
          title: "Full order lifecycle",
          text: "Pending → confirmed → preparing → out for delivery → delivered, with manual admin confirmation before dispatch",
        },
        {
          icon: "LayoutGrid",
          title: "Custom design system",
          text: "Hand-built Tailwind component library (cards, forms, badges, charts) - fully responsive, no UI kit dependency",
        },
      ],
      stats: [
        { value: "69", label: "Wilayas supported" },
        { value: "2", label: "Admin roles" },
        { value: "100%", label: "Responsive UI" },
        { value: "REST", label: "API backend" },
      ],
      about:
        "This project was developed as part of my Licence in ISIL (Ingénierie des Systèmes d'Information et Logiciels), reproducing a real multi-branch restaurant ordering system - from customer-facing UX to a secure, role-scoped admin backend - with particular attention to data integrity, access control, and honest handling of what is and isn't a real production payment flow.",
      meta: {
        type: "Licence Graduation Project",
        year: "2024",
        stack: "React + Node.js + Supabase (PostgreSQL)",
        status: "In Development",
      },
      note: "Licence ISIL (Ingénierie des Systèmes d'Information et Logiciels) graduation project, 2024.",
    },
  ],
  process: [
    "Understand the business rules and user roles",
    "Design the database, pages, forms, and workflows",
    "Build the front end, back end, and validation logic",
    "Test, deploy, and polish the final experience",
  ],
};
